FROM --platform=linux/amd64 amazonlinux:2 AS base

RUN yum install -y python3

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install \
    venv-pack==0.2.0 \
    psycopg2-binary==2.9.5 \
    boto3==1.26.13 \
    certifi==2022.9.24

# Replace Mozilla's carefully curated collection of Root Certificates with rds-ca-2019-root.pem
COPY rds-ca-2019-root.pem $VIRTUAL_ENV/lib/python3.7/site-packages/certifi/cacert.pem

RUN mkdir /output && venv-pack -o /output/pyspark_db.tar.gz

FROM scratch AS export
COPY --from=base /output/pyspark_db.tar.gz /